export const rooms = [
  {
    name: "The Sapphire Suite",
    pricePerNight: 168,
    description:
      "Indulge in the opulence of our Sapphire Suite, where luxury meets comfort. This room features a king-sized bed, a state-of-the-art entertainment system, and a private balcony with breathtaking views.",
    address: "Terpvej 21, 6630  Øster Lindet  Vejen, Denmark",
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133212/hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
      },
      {
        public_id: "hosteldk/mock/cbyg5dztud4z8gvxeed7.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/cbyg5dztud4z8gvxeed7.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "The Tranquility Twin",
    pricePerNight: 242,
    description:
      "Designed for relaxation, the Tranquility Twin offers two plush twin beds, soothing decor, and a serene atmosphere, perfect for unwinding after a day of adventure.",
    address: "Nørreballevej 5, 5900  Tryggelev  Langeland, Denmark",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/rzfyup3x1gwnwke33zxl.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/rzfyup3x1gwnwke33zxl.jpg",
      },
      {
        public_id: "hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "The Vintage Veranda",
    pricePerNight: 85,
    description:
      "Step back in time with the Vintage Veranda room, boasting antique furnishings, a claw-foot tub, and a cozy veranda to enjoy your morning coffee.",
    address: "Skovmarksvej 14, 4100  Vetterslev  Ringsted, Denmark",
    guestCapacity: 3,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/cbyg5dztud4z8gvxeed7.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/cbyg5dztud4z8gvxeed7.jpg",
      },
      {
        public_id: "hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133212/hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "The Executive Escape",
    pricePerNight: 95,
    description:
      "Tailored for the business traveler, the Executive Escape provides a spacious work desk, high-speed internet, and an ergonomic chair to ensure productivity and comfort.",
    address: "Gartnervænget 4, 7752  Snedsted  Thisted, Denmark",
    guestCapacity: 5,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/up4razicjmlpyoc0zfjh.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/up4razicjmlpyoc0zfjh.jpg",
      },
      {
        public_id: "hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133212/hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
      },
      {
        public_id: "hosteldk/mock/mntbfiwgridfhghhhifl.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/mntbfiwgridfhghhhifl.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "The Romantic Retreat",
    pricePerNight: 105,
    description:
      "Celebrate love in our Romantic Retreat, featuring a four-poster bed, soft lighting, and a luxurious jacuzzi tub for two.",
    address: "Bjergsnæs Mose 13, 8800  Søndermark  Viborg, Denmark",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/qzpy9qcfyojbbksfuchs.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/qzpy9qcfyojbbksfuchs.jpg",
      },
      {
        public_id: "hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
      },
    ],
    category: "King",
    reviews: [],
  },
  {
    name: "The Garden Getaway",
    pricePerNight: 36,
    description:
      "Surrounded by greenery, the Garden Getaway offers a peaceful respite with its own private garden, a comfortable daybed, and nature-inspired decor.",
    address: "Kornskyldvej 31, 2300  Sundbyvester  Copenhagen, Denmark",
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/mntbfiwgridfhghhhifl.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/mntbfiwgridfhghhhifl.jpg",
      },
    ],
    category: "Twins",
    reviews: [],
  },
  {
    name: "The Seaside Sanctuary",
    pricePerNight: 82,
    description:
      "Wake up to the sound of waves in the Seaside Sanctuary, where each room faces the sea and comes with a private terrace to soak in the sunsets.",
    address: "Tesdorpfsvej 13, 2000  Godthåb  Frederiksberg, Denmark",
    guestCapacity: 5,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133211/hosteldk/mock/edwkz4yp0pvcpa233p9h.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
  {
    name: "The Artist’s Atelier",
    pricePerNight: 76,
    description:
      "A haven for creatives, the Artist’s Atelier is adorned with inspiring art, offers ample natural light, and includes an easel for those who wish to paint.",
    address: "Voldmestergade 8, 2100  Indre By  Copenhagen, Denmark",
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: "hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133212/hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
      },
      {
        public_id: "hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
        url: "https://res.cloudinary.com/dv7nhvy8e/image/upload/v1714133212/hosteldk/mock/qgssfkp2gmza8d3keqr2.jpg",
      },
    ],
    category: "Single",
    reviews: [],
  },
];
